### PR TITLE
move PLT people to 'associates', auto-sort alumni

### PR DESCRIPTION
**Pull request by bennn**
- Move Mattew, Robby, etc to the "Former Associates" section. Maybe they shouldn't be there at all either, but I like having lots of names here.
- Require a year for each alumnus. I guessed for Mark Krentel, Joe Marshall, and Mario Latendresse.
- Sort alumni by year & name (lexicographic), organize into columns.

### CODE REVIEW

**Comment by schuster** [comment]
A few fixes:
- Ahmed graduated in 2014, not 2012
- Why make years required? I don't think they even make sense for "former associates"
- Similarly, I don't know that listing dissertations for former associates adds anything. Their dissertations weren't done at Northeastern, so what do those have to do with this page?
- David Van Horn is getting put into a 4th column for some reason. There's probably a bug in `alumnus-list`

**Comment by bennn** [comment]
The years are for ordering & they show we have a long and busy history.

I'll drop the extra dissertations.

**Comment by bennn** [comment]
(Let me know if you still see 4 columns, it looks ok for me on chrome & firefox)

**Comment by schuster** [comment]
Yep, the extra column issue appears to be fixed.

Could you just fix the merge conflicts and we'll pull it in?

**Comment by bennn** [comment]
All merged.

**Pull request closed without merging**
