### PR TITLE
New blog post: ICFP 2016 student volunteers

### PR DESCRIPTION
**Pull request by gasche**

### CODE REVIEW

**Comment by bennn** [comment]
Will post this today.
(But before I do, I'm going to try & set up that `dev` branch and only take 8017a26 from here :) )

**Comment by bennn** [comment]
Oh hey, should this include a memo about PLMW@ICFP?

**Comment by gasche** [comment]
> Oh hey, should this include a memo about PLMW@ICFP?

Of course, I just added a last paragraph about PLMW. Thanks for the idea!

**Comment by bennn** [comment]
Merged in https://github.com/nuprl/nuprl.github.io/commit/ac89a3e818084e999a2deb92eb09989de8b3b745 and online [here](http://prl.ccs.neu.edu/blog/2016/06/07/icfp-2016-looking-for-student-volunteers/)!

**Pull request closed without merging**
