### PR TITLE
Blog post nepls

### PR DESCRIPTION
**Pull request by gasche**
I was looking for author support but I haven't found it. This is tracked by the frog feature request greghendershott/frog#162 .

### CODE REVIEW

**Comment by bennn** [comment]
For now, want to use a tag `by Gabriel Scherer` ?

**Comment by bennn** [comment]
(If so, could you also add a `by Ben Greenman` tag to the first post? Then lets merge.)

**Comment by gasche** [comment]
Done in 62912dd1f8399fab7a2da22f37b99f870d84ea86 .

**Comment by bennn** [comment]
https://github.com/nuprl/nuprl.github.io/commit/bcfd2fedcaeaed63cd5c6815261d268a2c96f628 👍

**Comment by schuster** [comment]
Correction for others like me following this thread: the authorship issue is greghendershott/frog#162 .

**Pull request closed without merging**
